using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using ToolsConsole.Domain.Abstractions;
using ToolsConsole.Domain.Entities;
using ToolsConsole.Infrastructure.Configuration;
using ToolsConsole.Infrastructure.Data;

namespace ToolsConsole.Infrastructure.Seed;

/// <summary>
/// 启动初始化：建库建表（EF EnsureCreated）+ 播种默认管理员 admin/123。
/// 说明：本 MVP 使用 EnsureCreated 自动建库建表；如需切换到 EF 迁移，
/// 请在具备网络的环境执行 `dotnet ef migrations add Init...` 并改用 MigrateAsync。
/// </summary>
public static class DbInitializer
{
    public static async Task InitializeAsync(IServiceProvider services, CancellationToken cancellationToken = default)
    {
        using var scope = services.CreateScope();
        var logger = scope.ServiceProvider.GetRequiredService<ILoggerFactory>().CreateLogger("DbInitializer");
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var passwordHasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher>();

        try
        {
            await db.Database.EnsureCreatedAsync(cancellationToken);
            await EnsureSystemConfigsTableAsync(db, cancellationToken);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "数据库建库/建表失败，请检查 ConnectionStrings:Default 与网络连通性");
            throw;
        }

        if (!await db.Users.AnyAsync(cancellationToken))
        {
            db.Users.Add(User.Create("admin", passwordHasher.Hash("123"), "系统管理员"));
            await db.SaveChangesAsync(cancellationToken);
            logger.LogInformation("已播种默认管理员账户 admin");
        }

        await SeedSystemConfigsAsync(db, services.GetRequiredService<Microsoft.Extensions.Configuration.IConfiguration>(), cancellationToken);
    }

    private static async Task SeedSystemConfigsAsync(
        AppDbContext db,
        Microsoft.Extensions.Configuration.IConfiguration configuration,
        CancellationToken cancellationToken)
    {
        var configs = new (string Key, string? Value, string Remark)[]
        {
            ("JwtSettings:Key", configuration["JwtSettings:Key"] ?? SystemConfigDefaults.JwtKey, "JWT 签名密钥"),
            ("Security:EncryptionKey", configuration["Security:EncryptionKey"] ?? SystemConfigDefaults.EncryptionKey, "连接配置密码落库存储密钥"),
            ("Security:DeliveryKey", configuration["Security:DeliveryKey"] ?? SystemConfigDefaults.DeliveryKey, "取串接口返回密文分发密钥"),
            ("Security:TransportKey", configuration["Security:TransportKey"] ?? SystemConfigDefaults.TransportKey, "前端密码传输加密密钥"),
            ("Security:TransportIv", configuration["Security:TransportIv"] ?? SystemConfigDefaults.TransportIv, "前端密码传输加密 IV"),
        };

        foreach (var (key, value, remark) in configs)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                continue;
            }

            if (!await db.SystemConfigs.AnyAsync(c => c.ConfigKey == key, cancellationToken))
            {
                db.SystemConfigs.Add(SystemConfig.Create(key, value, remark));
            }
        }

        await db.SaveChangesAsync(cancellationToken);
    }

    private static async Task EnsureSystemConfigsTableAsync(AppDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS system_configs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                config_key VARCHAR(120) NOT NULL,
                config_value TEXT NOT NULL,
                remark VARCHAR(500) NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ix_system_configs_config_key
            ON system_configs (config_key);
            """,
            cancellationToken);
    }
}
